### ISSUE TITLE
Create TileIndex to access all raster of a geojson

### ISSUE THREAD

**Issue by juliensam** [mapgears/sentinel_loading#1]
We need to have a TileIndex that gets updated everytime a new image is added for a geojson config file.

**Comment by benamarfaiez** [comment]
Si je vous ai bien compris, l'utilisateur doit définir une fréquence d'actualisation en premier lieu, c'est selon cette période alors qu'une requête HTTP, contenant toutes les informations concernant la zone d'intérêt "polygone", sera envoyée pour mettre à jour la configuration du fichier Geojeson.
Ce dernier autorisera le lancement de mises à jour de nouvelles images (on peut également ajouter une condition pour obtenir les images les plus nettes: le pourcentage du cloud doit être inférieur à une valeur prédéfinie). 
Enfin, mettre à jour le fichier shapefile qui contient le TileIndex.

![sequence diagram](https://user-images.githubusercontent.com/38057044/76125919-237dcb80-5ffe-11ea-86a3-c144743982aa.png)
